services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    container_name: backend_container
    image: mellow03/backend:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT= ${PORT}
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    container_name: frontend_container
    image: mellow03/frontend:latest
    ports:
      - "80:80"
    environment:
      - BASE_URL=${BASE_URL}
    deploy:
      restart_policy:
        condition: on-failure